config/routes.rb
PlaylisterXo::Application.routes.draw do
  devise_for :users
  resources :genres

  get "songs/makesome" => "songs#make_some", 
        :as => :make_songs
        
  resources :songs

  root 'artists#index'
  resources :artists

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
  has_many :genres, through: :songs

  before_save :sluggify

  def sluggify
    self.slug = self.name.gsub(" ", "-").downcase
  end

  def song_names=(names)
    names.each do |title|
      self.songs.build(title: title)
    end
  end

  def song_names
    Rails.cache.fetch([:artist, self.id, :songs]) do
      self.songs.map{|s| s.title }
    end
  end

  def to_param
    self.sluggify unless self.slug
    self.slug
  end

  def self.find(val)
    if val.to_i != 0
      super val
    else
      find_by(:slug => val)
    end
  end

  def self.find_by_genre(genre_name)
    #AREL
    joins(:songs => :genre)
    .where("genres.name ILIKE ?", genre_name)
  end

  def self.with_record_labels
    where.not(:record_label => :nil)
    #where("record_label is not null")
  end

  def self.with_specific_label(label)
    where(record_label: label)
  end

  def new_method
    true
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  skip_before_action :set_a_thing
  
  # GET /artists
  # GET /artists.json

  def index
    @artists = Artist.includes([:songs, :genres]).load
  end

  def label_index
    label = params[:label]
    @artists = Artist.with_label(label)
  end

  def api_call
    render json: @object
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    respond_to do |format|
      format.html { render 'show'}
      format.json { render json: @artist, serializer: OtherSerializer}
    end
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)
    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :record_label, :song_names => [])
    end

    def get_main_artist
      session[:main_artist] = @artists.first.name
    end
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :record_label %><br>
    <%= f.text_field :record_label %>
  </div>
  <div class="field">
    <h4>songs:</h4>
    <%= text_field_tag "artist[song_names][]" %><br>
    <%= text_field_tag "artist[song_names][]" %><br>
    <%= text_field_tag "artist[song_names][]" %><br>
    <%= text_field_tag "artist[song_names][]" %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
current user: <%= current_user %>
<h1>Listing artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Record label</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.record_label %></td>
        <td><% artist.songs.each do |song| %>
          <%= song.title %> <%= song.genre.name unless song.genre.nil? %>
          <% end %>
        </td>
        
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
Main Artist: <%= session[:main_artist] %>
<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Record label:</strong>
  <%= @artist.record_label %>
</p>
<p>
  <% cache @artist do %>
  <%= render 'songs/song_list', songs: @artist.songs %>
  <% end %>
</p>